version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - frontend

  frontend:
    image: node:14
    working_dir: /app/vueapp
    volumes:
      - ./app/vueapp:/app/vueapp
    command: sh -c "npm install && npm run serve"
    ports:
      - "8080:8080"
    depends_on:
      - backend
