# Generated by Django 5.0.1 on 2024-01-14 17:47

import api.models
import api.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, storage=api.storage.OverwriteStorage(), upload_to=api.models.customImagePath)),
            ],
        ),
    ]
