# Generated by Django 5.0.1 on 2024-01-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='desceiption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
