# Generated by Django 5.0.1 on 2024-02-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_onbording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
