# Generated by Django 5.0.1 on 2024-02-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_register_image_register_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
