# Generated by Django 5.0.1 on 2024-03-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsScoure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'News Scoure',
            },
        ),
    ]
