# Generated by Django 5.0.1 on 2024-03-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_newsscoure'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Fill Profile',
            },
        ),
    ]
